---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include = FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

```{r}
data(rest_inspec)

rest_inspec =
  rest_inspec %>% 
  select(boro, cuisine_description, dba, inspection_date, score) %>% 
  distinct %>% 
  rename(cuisine = cuisine_description) %>% 
  filter(cuisine %in% c("Chinese", "Italian", "Mexican", "Japanese", "Spanish",
                        "Indian", "Thai", "Korean")) %>% 
  mutate(
    inspection_date = as.character(inspection_date),
    year = substr(inspection_date, start = 1, stop = 4)
  )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Number of restaurants per cuisine by borough

```{r}
rest_inspec %>% 
  filter(boro != "Missing") %>% 
  select(dba, boro, cuisine) %>% 
  distinct(dba, boro, cuisine) %>% 
  count(boro, cuisine) %>% 
  mutate(cuisine = fct_reorder(cuisine, -n)) %>% 
  plot_ly(x = ~boro, y = ~n, color = ~cuisine, colors = "viridis") %>% 
  layout(
    xaxis = list(title = "Borough"),
    yaxis = list(title = "Number")
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Distribution of inspection scores by cuisine

```{r}
rest_inspec %>% 
  drop_na(score) %>% 
  mutate(cuisine = fct_reorder(cuisine, score)) %>% 
  plot_ly(y = ~score, color = ~cuisine, type = "box", colors = "viridis") %>% 
  layout(
    yaxis = list(title = "Score")
  )
```

### Mean inspection score by cuisine over time

```{r}
rest_inspec %>% 
  filter(year != 2013) %>% 
  drop_na(score) %>% 
  mutate(cuisine = fct_reorder(cuisine, score)) %>% 
  group_by(cuisine, year) %>% 
  summarise(mean_score = mean(score)) %>% 
  plot_ly(x = ~year, y = ~mean_score, color = ~cuisine,
          type = "scatter", mode = "lines+markers", colors = "viridis") %>% 
  layout(
    xaxis = list(title = "Year"),
    yaxis = list(title = "Mean Score")
  )
```

